#Application Configuration
server:
 port: 8091
 error:
    include-message: always

spring:
 h2:
  console:
   enabled: true
  
  datasource:
    url: jdbc:h2:mem:productDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIST=FALSE
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: 
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
       show-sql: true
       use_sql_comments: false
       format_sql: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTER:-%5p} %m%n"
